name: Bump version

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: bash sh/bump-version.sh
        env:
          GIT_USER: ${{ github.actor }}
          GIT_PASSWORD: ${{ secrets.GH_TOKEN }}
